### ISSUE TITLE
[FR]: A few features I would like to see

### ISSUE THREAD

**Issue by marksie1988** [minherz/copyright-inserter#25]
### Plugin Version

1.0.15

### What do you propose?

- Ability to add custom text
   -  for example i also put in the link to my project so people know where the file came from if it is copied
- Shortcut key, or at least add a field to allow one to be added
- Ability to insert copyright on newly created files
   -  would be nice if you could specify e.g. [python, typescript] in the config so it only applies to those file types

**Comment by minherz** [comment]
Hello @marksie1988 ,

Thank you for submitting this request. I would like to review each of your requests separately:

> Ability to add custom text

The plugin is intended for populating license headers to the files. The content of the license text is fixed beside the copyright part which can be customized. I can see how adding custom text somewhere above or after the license can be useful. However, this functionality is out of scope of this plugin. I apologies but I will not be able to add this to the plugin.

> Shortcut key, or at least add a field to allow one to be added

I agree that it is a useful function. I am glad to say that this function is an integral part of the plugin mechanism of VSCode. So, no coding is required. There is more than one way to define a key shortcut (aka keybinding) to a command. For example, you can follow these steps:

1. Press the combination of `Ctrl` + `Shift` + `P` to open the command palette.
2. Start typing "Copyright" to see the "Copyright: Insert Header" command of the plugin
3. Click on the cogwheel at the end of the line with the command to configure keybinding
4. Double-click anywhere on the link of the command to open the dialog that will remember the key combination you want.

The following interface is intuitive.

> Ability to insert copyright on newly created files

This is an interesting feature. Indeed, it should reduce the overhead of inserting a new copyright each time a user creates a new file. I received similar requests in the past. The reason why it is not implemented is because expected  frequency of new files in an average project is relatively low, except maybe a new project. With keybinding, this functionality saves a user up to 3 (or 4) key pressing per file.
Adding this functionality means additional development and maintenance times and overall complexity of code increase,  into developing this functionality means 
Although I admit that it is a nice-to-have feature, in the current use cases I find the that it does not justify the required investment. You are welcome to develop and submit this functionality. If it does not require significant redesign and is resilient to VSCode development roadmap I will be glad to incorporate it into the plugin.

I hope that my response explains why I will not be able to implement your suggestions. I am closing this request for now. If you have arguments that demonstrate a use case that refute the above arguments, feel free to reopen this issue and provide additional information.

Thank you
