### ISSUE TITLE
The tool does not work in remote container

### ISSUE THREAD

**Issue by mateus-amarante** [minherz/copyright-inserter#3]
I was not able to use the extension when vscode is attached to a docker container using [Remote Containers](https://code.visualstudio.com/docs/remote/containers). I could use it in the host machine without any problem.

**Comment by minherz** [comment]
Hi,
Thank you for letting know about the problem with the support of the VSCode remote development. Can you provide additional information such as any console output that extension prints? It will be useful to know [where](https://code.visualstudio.com/docs/remote/containers#_managing-extensions) the extension is installed locally or in a container.
It will help if you can provide more info about OS in container and on client and a version of VSCode.

Thank you,
minherz

**Comment by mateus-amarante** [comment]
I think it is installed in the container. I can see the extensions installed in the `$HOME/.vscode-server/extensions/` folder inside the container.

![Screenshot from 2020-11-02 18-50-01](https://user-images.githubusercontent.com/7409263/97923134-4a7ecf80-1d3c-11eb-8c30-cde3cb761c85.png)

- **Container OS:** Ubuntu Focal
- **VSCode Version:** 1.50.1

**Comment by mateus-amarante** [comment]
When I run in debug mode I get the following message:

`copyright-header-inserter: failed to find configuration for language $language`

I tested with cpp and python languages

**Comment by minherz** [comment]
Thank you, @mateus-amarante. It seems that the problem is that the extension is configured to run in the container when it is like codesnipet extensions should run locally where it can access the language configurations. Unless you have it explicitly configured it in the `.devcontainer.json` or `.devcontainer/devcontainer.json` file in the `"extensions"` field.
I will work to check that the extension's manifest doesn't describe it as one that should run in a remote workspace and fix it. I appreciate it if you can confirm that your workspace configuration is not configured to run this extension explicitly on a remote / container.

**Comment by mateus-amarante** [comment]
I didn't define a `.devcontainer` configuration. I am attaching the vscode to a container that is already running.

**Comment by minherz** [comment]
Thanx for the update. I have released the package with updated manifest file as 1.0.5 version. Will you be kind to run a test for me since I do not have capability to create a development setup with a remote container to test it. If the quick testing proves working -- you will see the extension to be launched as a local extension then you will be able to use it as designed and I will take it that the manifest update solves the problem.
Otherwise, I will try looking into the problem more closely this weekend.

**Comment by mateus-amarante** [comment]
Now it works beautifully. Thanks very much for the quick reply and fix.
